services:
  games-api:
    image: jakobjakob/games-api:1.2
    container_name: games-api
    restart: unless-stopped
    ports:
      - "3000:3000"
    networks:
      - web
    volumes:
      - ./database:/app/database/
networks:
  web:
    external: true
