services:
  games-api:
    image: jakobjakob/games-api:1.0
    container_name: games-api
    restart: unless-stopped
    ports:
      - "4000:4000"
    networks:
      - web
volumes:
  portainer_data:
networks:
  web:
    external: true
