services:
  reverse-proxy:
    image: nginx:1.15-alpine
    container_name: nginx-proxy
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    networks:
      -  web
    volumes:
      - ./conf.d:/etc/nginx/conf.d:ro
      - ../static-site/html/:/usr/share/nginx/static/:ro
      - ./data/certbot/www:/var/www/certbot       # ACME challenge files
      - ./data/certbot/conf:/etc/letsencrypt      # Certbot’s cert store
  certbot:
    image: certbot/certbot
    container_name: certbot
    restart: unless-stopped
    volumes:
      - ./data/certbot/www:/var/www/certbot
      - ./data/certbot/conf:/etc/letsencrypt
    depends_on:
      - reverse-proxy
networks:
  web:
    external: true
