services:
  reverse-proxy:
    image: nginx:1.15-alpine
    container_name: nginx-proxy
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    networks:
      -  web
    volumes:
      - ./conf.d:/etc/nginx/conf.d:ro
      - ../static-site/html/:/usr/share/nginx/static/:ro
      - /etc/letsencrypt/ssl/fullchain.pem:/etc/nginx/ssl/fullchain.pem
      - /etc/letsencrypt/ssl/privkey.pem:/etc/nginx/ssl/privkey.pem
  certbot:
    image: certbot/certbot
    container_name: certbot
    restart: unless-stopped
    network_mode: "host"
    volumes:
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
    depends_on:
      - reverse-proxy

networks:
  web:
    external: true
